"""add whatsapp fields to users and contacts

Revision ID: 723492ba17b7
Revises: 29efdb088152
Create Date: 2026-04-09 12:10:21.734534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723492ba17b7'
down_revision: Union[str, None] = '29efdb088152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('whatsapp_phone', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('whatsapp_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('whatsapp_about', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('whatsapp_avatar_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('whatsapp_bio_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_contacts_whatsapp_phone'), 'contacts', ['whatsapp_phone'], unique=False)
    op.add_column('users', sa.Column('whatsapp_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('whatsapp_connected', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('whatsapp_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_last_synced_at')
    op.drop_column('users', 'whatsapp_connected')
    op.drop_column('users', 'whatsapp_phone')
    op.drop_index(op.f('ix_contacts_whatsapp_phone'), table_name='contacts')
    op.drop_column('contacts', 'whatsapp_bio_checked_at')
    op.drop_column('contacts', 'whatsapp_avatar_url')
    op.drop_column('contacts', 'whatsapp_about')
    op.drop_column('contacts', 'whatsapp_name')
    op.drop_column('contacts', 'whatsapp_phone')
    # ### end Alembic commands ###
