"""Add twitter_username and telegram_username to users

Revision ID: aaa04d9b4d92
Revises: 843b7c10738e
Create Date: 2026-03-05 12:39:41.614860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa04d9b4d92'
down_revision: Union[str, None] = '843b7c10738e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'twitter_username')
    # ### end Alembic commands ###
