"""add meta facebook instagram fields

Revision ID: ad8670aa51dd
Revises: 723492ba17b7
Create Date: 2026-04-10 13:07:37.175482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad8670aa51dd'
down_revision: Union[str, None] = '723492ba17b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_events_platform', table_name='sync_events')
    op.drop_index('ix_sync_events_user_id', table_name='sync_events')
    op.drop_table('sync_events')
    op.add_column('contacts', sa.Column('whatsapp_avatar_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('facebook_id', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('facebook_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('facebook_avatar_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('instagram_id', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('instagram_username', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('instagram_avatar_url', sa.String(), nullable=True))
    op.drop_index('uq_contacts_telegram_user_id_per_user', table_name='contacts', postgresql_where='(telegram_user_id IS NOT NULL)')
    op.drop_index('uq_contacts_telegram_username_per_user', table_name='contacts', postgresql_where='(telegram_username IS NOT NULL)')
    op.create_index(op.f('ix_contacts_facebook_id'), 'contacts', ['facebook_id'], unique=False)
    op.create_index(op.f('ix_contacts_instagram_id'), 'contacts', ['instagram_id'], unique=False)
    op.alter_column('extension_pairings', 'code',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('interactions', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_organizations_domain', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.alter_column('tag_taxonomies', 'categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.add_column('users', sa.Column('meta_connected', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('meta_connected_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('meta_sync_facebook', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('meta_sync_instagram', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'meta_sync_instagram')
    op.drop_column('users', 'meta_sync_facebook')
    op.drop_column('users', 'meta_connected_name')
    op.drop_column('users', 'meta_connected')
    op.alter_column('tag_taxonomies', 'categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_domain', 'organizations', ['domain'], unique=False)
    op.drop_column('interactions', 'extra_data')
    op.alter_column('extension_pairings', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_index(op.f('ix_contacts_instagram_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_facebook_id'), table_name='contacts')
    op.create_index('uq_contacts_telegram_username_per_user', 'contacts', ['user_id', sa.text('lower(telegram_username::text)')], unique=False, postgresql_where='(telegram_username IS NOT NULL)')
    op.create_index('uq_contacts_telegram_user_id_per_user', 'contacts', ['user_id', 'telegram_user_id'], unique=False, postgresql_where='(telegram_user_id IS NOT NULL)')
    op.drop_column('contacts', 'instagram_avatar_url')
    op.drop_column('contacts', 'instagram_username')
    op.drop_column('contacts', 'instagram_id')
    op.drop_column('contacts', 'facebook_avatar_url')
    op.drop_column('contacts', 'facebook_name')
    op.drop_column('contacts', 'facebook_id')
    op.drop_column('contacts', 'whatsapp_avatar_url')
    op.create_table('sync_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('records_created', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('records_updated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('records_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sync_events_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sync_events_pkey')
    )
    op.create_index('ix_sync_events_user_id', 'sync_events', ['user_id'], unique=False)
    op.create_index('ix_sync_events_platform', 'sync_events', ['platform'], unique=False)
    # ### end Alembic commands ###
